### ISSUE TITLE
GL30 renderer doesn't support 'drawScaled'

### ISSUE THREAD

**Issue by JonnyH** [pmprog/OpenApoc#29]

**Comment by pmprog** [comment]
Is there a way we can get the renderers to fallback to the Allegro routines if they aren't implemented? or does your renderer system make that impossible?

**Comment by JonnyH** [comment]
Its difficult to be realistically impossible. Allegro's draw functions use opengl and it doesn't like two things using opengl at the same time as they'll stomp over each others state machines (unless you use multiple contexts, but then switching contexts is often expensive, which would be necessary before every allegro callback, plus sharing the textures between contexts is also a massive pain too). Generally this shouldn't be hard, the scale version should be near trivial, I just need to get off my arse and actually do it.

**Comment by pmprog** [comment]
That's fine, I was just figuring if there was a general fallback, and people added other rendering back ends (for whatever reason?) then there'd always be a "fallback" when they don't implement something.

But yeah, I appreciate it's not that simple; and I guess there's no great rush at the minute. I'm slowly getting back into it, and currently plodding through the Ufopaedia

**Comment by JonnyH** [comment]
I can have an allegro/sw 'fallback', but the renderers are all or nothing as implemented. Partial fallbacks are always hard, and often 'slower' than just thunking everything down to sw....

**Comment by pmprog** [comment]
An Allegro/sw renderer would be nice (because then we'll support non-GL3/GLES2 devices)

Not essential at this point in time though
