### ISSUE TITLE
Compile Error on Visual Studio 2013

### ISSUE THREAD

**Issue by pmprog** [pmprog/OpenApoc#38]
#### Error
Error	18	error C2065: 'rc' : undeclared identifier	openapoc\dependencies\physfs\src\archiver_iso9660.c	712	1	physfs

#### Fix
archiver_iso9660.c - Line 709 should be braced
```
    if (bytesleft < len)
		{
        len = bytesleft;
		}
```

## Allegro Error
Error	14	error C2664: 'char *_al_sane_strncpy(char *,const char *,size_t)' : cannot convert argument 2 from 'const WCHAR [260]' to 'const char *'	openapoc\dependencies\allegro\src\win\wjoydxnu.cpp	485	1	allegro5

**Comment by pmprog** [comment]
Sent @JonnyH a pull request for the Physfs fix. Not sure how to handle the Allegro build

**Comment by JonnyH** [comment]
The allegro issue is that it seems that it doesn't expect UNICODE to be defined for this file, so the DX functions should stub to the ASCII versions.

Maybe changing the allegro build so it's not Unicode enabled will fix this? It seems allegro uses the Unicode functions explicitly in some places, but fails if they're enabled globally.

**Comment by pmprog** [comment]
Okay, will try that. Cheers

**Comment by pmprog** [comment]
Works :) Will push the project settings into repo

**Comment by JonnyH** [comment]
Might be interesting to check if non-ascii characters still work in the title etc. when disabling unicode....

**Comment by pmprog** [comment]
Maybe, if I remember a bit later I'll give it a quick check
