### ISSUE TITLE
Threading GameCore loading

### ISSUE THREAD

**Issue by pmprog** [pmprog/OpenApoc#55]
I want to thread BootUp::CreateGameCore so we can display a splash and that spinning disc icon to feel more responsive.

However, when I tried this, it crashed when it tried to move from the BootUp to the Menu stage. Can we look at this and get it fixed

**Comment by JonnyH** [comment]
https://github.com/JonnyH/OpenApoc/tree/WIP/test-async-loading seems to fix this (We can rebase on master instead of my ruleset - it should be separable and forgot which branch I was on :)

**Comment by pmprog** [comment]
We're in and working
