### ISSUE TITLE
Minor Vehicle pathing bug

### ISSUE THREAD

**Issue by ShadowDancer** [pmprog/OpenApoc#73]
https://dl.dropboxusercontent.com/u/12185236/pathing.png

**Comment by idshibanov** [comment]
Can you elaborate a bit more? Not sure what's wrong with the paths.

**Comment by ShadowDancer** [comment]
Hawk should continue as pointed out by yellow arrow. Instead it goes down and then up for some reason.

**Comment by JonnyH** [comment]
I think this might be 'expected' is something happened to be in the tile it avoided when it started it's route.
If that is the cause, I'm not sure if constantly re-routing would be a good idea or not (as the current implementation has a relatively high cost)

**Comment by ShadowDancer** [comment]
No, it doesn't. Every time I move between those 2 buildings route is the same.
